[package]
name = "shapes"
version = "0.1.0"
authors = ["piaoger"]

[dependencies]
iron = "*"
router = "*"
serde = "0.4.1"
serde_macros = "*"
websocket = "*"
staticfile = "*"
mount = "*"
anymap = "*"
rand = "*"